### ISSUE TITLE
Add last measurement field to sites and plots

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#102]
We need a sortable last measurement field in the sites and plots tables.

**Comment by almasaeed2010** [comment]
- [ ] Create a migration to add last_measurement (nullable date) field to sites table
- [ ] Create a migration to add last_measurement (nullable date) field to plots table
- [ ] Create command to fill the last_measurement fields for sites and plots
  - The last measurement field = the greatest measurements.date value (not the last value)
- [ ] Every time a measurement is added or updated, the site and plot last_measurement fields should be checked to see if they need updating as well.

**Comment by almasaeed2010** [comment]
Once the functionality is implemented, display the field on the sites and plots pages and make sure it's sortable. In fact, I'd make it the default field sorted in desc order.

**Comment by jwest60** [comment]
Done. #106
