### ISSUE TITLE
Users page

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#11]
User management page for admin

**Comment by jwest60** [comment]
Not sure what we want displayed, do we just want to start by having a page where the owner can see all existing sites?

**Comment by almasaeed2010** [comment]
Want a new page that lists all users to administrators

**Comment by almasaeed2010** [comment]
- [ ] New "Users" tab in sidebar 
- [ ] New page at `/app/users`
- [ ] Page should display a searchable table of users
  - [ ] Show the user avatar, name, email, registration date in human readable format using `diffForHumans()`.
- [ ] Name should be clickable to take the admin to the user's profile page (see #12)
