### ISSUE TITLE
Dashboard should have list of sites

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#114]
The list should be limited to 10 items and ordered by last_measured_at (ascending) so that sites not visited recently should be at the top

**Comment by almasaeed2010** [comment]
Have a card on the dashboard that shows a table of sites along with the last measurement field.

allow the table to be sortable but default to (last_measured_at, asc).

I'd suggest that this card takes only half the width of the page:
```
<div class="row">
  <div class="col-lg-6">
    ... our card here ...
   </div>
</div>
```

**Comment by jwest60** [comment]
Added with #135
