### ISSUE TITLE
Auto generate Excel sheets for each site

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#117]
Peter shared some examples of sheets that we could generate 

- [yancey.2018.data.scanned(1).pdf](https://github.com/statonlab/AVIDWeb/files/4589044/yancey.2018.data.scanned.1.pdf)
- [bullock.2018.data.scanned.pdf](https://github.com/statonlab/AVIDWeb/files/4589043/bullock.2018.data.scanned.pdf)

**Comment by almasaeed2010** [comment]
Using Laravel Excel, we can generate sheets that have the columns similar to the attached files above. The links should be accessible on each site. The file should contain instructions and site information in the top few lines. The file should be importable.

**Comment by jwest60** [comment]
Added a method of exporting and importing spreadsheets.

![image](https://user-images.githubusercontent.com/32902460/82590895-7cc0ba00-9b6c-11ea-96b9-de56fbc42e09.png)

Exported spreadsheets will appear in the following form.

![image](https://user-images.githubusercontent.com/32902460/82591009-a7127780-9b6c-11ea-8a56-b6a1f0e0895f.png)

Users will fill out the last two columns with the date of collection and the height of their measurement.

When the data has been filled out, you can use the importer to auto-generate measurements. The spreadsheet will be validated to ensure there are no problems and provide feedback if there is.

![image](https://user-images.githubusercontent.com/32902460/82591122-d5905280-9b6c-11ea-84b1-8dfcda4b74d6.png)

**Comment by jwest60** [comment]
Added with #134
