### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#12]
Profile page for users

**Comment by jwest60** [comment]
A profile page already exists, what do we want added to it?

**Comment by almasaeed2010** [comment]
This is where the users page (#11) would lead to when a user name is clicked.

- [ ] Display the user info just like WFID
- [ ] Display a list of sites (same as sites page)
  - [ ] Allow search
  - [ ] When the title is clicked, take the admin to the site's page

**Comment by almasaeed2010** [comment]
We also want the ability to change the user's role just like treessnap

**Comment by jwest60** [comment]
Clicking a user name in the users page takes you to profile page #43 

User role can be changed on profile page #51
