### ISSUE TITLE
Dashboard Sites Issues

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#147]
A couple of issues in the dashboard's sites card:

- There is an extra `<th>` or `<td>` in the table's `<thead>`. 
  - <img width="578" alt="Screen Shot 2020-05-26 at 11 02 47 AM" src="https://user-images.githubusercontent.com/1512664/82916886-a4cf6500-9f40-11ea-86ad-e2c095ce2ba6.png">
- It would be nice to have a header on the cart that says "Sites"

**Comment by jwest60** [comment]
Done. #150
