### ISSUE TITLE
Remove the titles from the plots, plants and measurements views

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#148]
See image below. Those titles are not necessary in my opinion. I think removing them would give the user more vertical space to work with.

<img width="1165" alt="Screen Shot 2020-05-26 at 11 07 13 AM" src="https://user-images.githubusercontent.com/1512664/82917256-3212b980-9f41-11ea-978a-3b59052abc63.png">

**Comment by jwest60** [comment]
Done. #149
