### ISSUE TITLE
Chart data needs to be built from JS side

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#160]
We are merging #158 for the demo but we will need to do small changes:

The code that builds the chart on the dashboard is combining front-end and back-end responsibilities. PHP should be responsible for building the raw data needed to build the chart. It is not responsible for setting titles, modifying font sizes or colors. The JS side should take the data given by the server and customize the look and feel of the chart as needed.

- [x] Remove chart configuration from PHP
- [x] PHP should return raw data such as `[ year => [height1, height2] ]` along with any other objects/data needed to create the chart
- [x] JS should take the data and format it the way Apex charts wants and add any font sizing and color configuration.

Using this structure we'd be able to switch the charting library without having to change the PHP code. This also removes styling responsibilities from the PHP side which, unlike JS, doesn't have the ability to access css or other style variables.

**Comment by jwest60** [comment]
Fixed #182. The controller now returns the following data
```
            'xaxis' => $years,
            'data' => [
                [
                    'protected' => $protected,
                    'count' => $protected_count,
                ],
                [
                    'unprotected' => $unprotected,
                    'count' => $unprotected_count,
                ],
            ]
```
