### ISSUE TITLE
Stats page changes

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#216]
- [x] remove quadrants
- [x] Add state filter
- [x] Add county filter (counties should be loaded only when a state is selected
- [x] Add protection filter
- Not sure how to handle the town yet but it looks like we might have to look into "wild life managment unit" data that can be extracted from a gis layer.

This is the shape file:
[wmu shape.7z.zip](https://github.com/statonlab/AVIDWeb/files/4793066/wmu.shape.7z.zip)

**Comment by jwest60** [comment]
we need a way to allow users to create these charts for group sites and allow admins to create it for all/any available site

add a little dropdown above sites that allows you to filter by `My Sites Only (default)` , `All Sites (Admin View)`, `Group Name`

**Comment by jwest60** [comment]
Done. #232 #233
