### ISSUE TITLE
Stats Page 

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#241]
- [x] Add loading indicator next to chart title.
- [x] Replace "container" class with "container-fluid" so the the chart can be expanded. Sometimes we want more space to display the chart but the container class limits it to 1250px (see attached screenshot)
- [x] would be nice to have a way to limit the number of years so they can pick what years to show. This can be a simple min max year text inputs.

![Screen Shot 2020-06-29 at 3 56 29 PM](https://user-images.githubusercontent.com/1512664/86049987-1eb3ac00-ba21-11ea-8a00-32b4ba5129eb.png)

**Comment by jwest60** [comment]
Done. #270
