### ISSUE TITLE
Protection filter on stats page

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#252]
The current protection filter simply removed protected plots or unprotected plots from the chart. What we need instead is the ability to select all plots in a site that has only protected plots, only unprotected plots or only both protected and unprotected plots. 

This query can be easily achieved by using whereHas or whereDoesn'tHave on the Site level rather than filtering on the Plot level.

**Comment by jwest60** [comment]
Done. #260
