### ISSUE TITLE
Ability to share sites

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#253]
On each site, we need a way to share the site with individual users. This has a few tricky parts that we may or may not want to worry about:

- Should we send an email and have the user accept the invitation to access a site? (GitHub does this with repos)
- Do we ask the user to enter an email address? or pick a user from a dropdown list? (Github allows you to pick from a list if you have a the full email address/username, do we want to do this as well to protect privacy?)
- We do need permissions on each share record. That is, the owner of the site should be able to decide whether the person they share a site with has permission to view or view and edit. I think we can assume if you can edit, then you can delete just to keep things simple.

**Comment by jwest60** [comment]
Done. #268
