### ISSUE TITLE
Chart text doesn't show correctly

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#254]
Suggested solutions:
- Change the text to black
- Can we break the text to a new line for the (n=) part?
- Ability to select the years we are interested in. Maybe we can have checkboxes at the bottom of the chart to toggle the years we do/don't want? That way a user can see the change from 2010 to 2020 for example without having to see all the years in between.

<img width="779" alt="Screen Shot 2020-07-01 at 10 07 02 AM" src="https://user-images.githubusercontent.com/1512664/86253484-9d742a80-bb82-11ea-8616-1aa3afeb4d1e.png">

**Comment by jwest60** [comment]
Text color has been changed and moved N= to a new line. Still waiting on a years filter.

**Comment by jwest60** [comment]
Done. #270
