### ISSUE TITLE
Importer might need changing

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#262]
Currently, the data importer uses an old DB structure. We need to go through it and make sure it still works before we reload the data from the old site to the new site.

**Comment by jwest60** [comment]
As far as I can see, the importer works as is. I ran the importer with both the spring wildflowers and woody seedlings and didn't encounter any issues.

I've made a change that will update some fields after importing (i.e. the last_measured_at and wmu fields). After running these commands, the imported resources should contain all the same information as any other resource.
