### ISSUE TITLE
Automatic reminders

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#274]
This issue is a bit complex. We want 2 reminders to be automatically created at (11 months) and (11 months and 3 weeks) for each site. 

The following users get assigned a reminder:
- An owner of a site
- A user who has a site shared with them
- I will intentionally ignore group sharing since it's far more complicated to deal with it and probably not necessary.
- Administrators will NOT get reminders for all sites. That's just annoying.

Make sure reminders go out only to verfied email addresses. We don't want to get blocked because of sending a ton of bounced emails.

**Comment by jwest60** [comment]
Done. #282
