### ISSUE TITLE
Species creator on the sites form should show the plant type

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#278]
Currently, when creating a new species from within the sites form, no plant type gets designated. My suggestion would be to rework this field such that when a new species is needed, the user has to enter both the plant type and the species. However, they were ok with simply selecting Woody Seedling when it's being added to the overstory field. I dislike this because it's not clear that this is what we are doing. I recall the plant form had a better way of creating species. Can we maybe replicate that for the sites form? There are 2 fields that require species, so we might have to do a little trick where if a user clicks "new species", the rest of the form disappears allowing the user to focus on creating the species.

<img width="491" alt="Screen Shot 2020-07-15 at 9 55 54 AM" src="https://user-images.githubusercontent.com/1512664/87553826-62452180-c681-11ea-8206-5d28a13c51a1.png">

**Comment by jwest60** [comment]
Done. #281
