### ISSUE TITLE
Importer errors

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#295]
- [x] We need the file Peter has been using to upload new data so we can test the importer.
- [x] Tell the user when a plot or a plant does not exist and ask them to create it first

**Comment by jwest60** [comment]
Resolved the issue that was causing the importer errors and sent an e-mail to Peter asking him to try importing again.

**Comment by jwest60** [comment]
It appears that Peter was able to successfully import data from several files so I'm considering the importer issues to be fixed with #304
