### ISSUE TITLE
Species merge

### ISSUE THREAD

**Issue by jwest60** [statonlab/AVIDWeb#340]
We have many duplicate species on the live site that should be merged into one

**Comment by mestato** [comment]
From the file AVID-Spring-Wildflowers.csv  the species column contains only three species:
- Indian Cucumber Root
- Jack in the Pulpit
- Trillium

Those are all spring wildflowers. From the file AVID-Woody-Seedlings.csv, there are more species:
- Apple Sp.
- Ash
- Ash, White
- Ash, black
- Aspen
- Autumn/Russian Olive
- Beech, American
- Birch Sp.
- Birch, Gray
- Birch, Paper
- Birch, Yellow
- Blackgum
- Butternut
- Cherry
- Cherry, Black
- Chestnut, American
- Hickory Sp.
- Hickory, Shagbark
- Hophornbeam, E. Ironwood, Ostrya
- Hornbeam, Amer. Carpinus
- Maple, Red
- Maple, Striped
- Maple, Sugar
- Mountain Laurel
- Oak
- Oak, Chestnut
- Oak, Northern Red
- Oak, Red
- Oak, Swamp White
- Oak, White
- Pine, Eastern White
- Sassafras
- Serviceberry
- Spicebush
- Witch Hobble

Those are all woody seedlings. So I don't see anything mislabeled.

**Comment by almasaeed2010** [comment]
Done
