### ISSUE TITLE
Go through the original site and make note of missing fields

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#35]
We need to walk through all forms in the current site (aviddeer.com) and make sure all form fields have are available on the new site.

**Comment by jwest60** [comment]
#### Site Form
- [ ] Site Name
- [ ] State
- [ ] County
- [ ] Town
- [ ] Owner Name and Contact Information
- [ ] Approximate basal area
- [ ] Average overstory tree diameter
- [ ] List the 4 most common overstory tree species in the stand
- [ ] List the 4 most common seedling or shrub species in the stand
- [ ] Map of stand

#### Plot Form
- [ ] Plot #
- [ ] Name(s) of Recorders
- [ ] Latitude
- [ ] Longitude
- [ ] Basal Area
- [ ] Ground and shrub cover
- [ ] Subcanopy
- [ ] Canopy
- [ ] Is plot enclosed or protected from deer?
- [ ] If yes, for how many growing seasons?

#### Spring Wildflower Form
- [ ] Tag #
- [ ] Species
- [ ] Quadrant

#### Woody Seedling Form
- [ ] Tag #
- [ ] Species
- [ ] Quadrant

#### Canada Mayflower Form
- [ ] Date
- [ ] Number of stems
- [ ] Number of flowers

**Comment by jwest60** [comment]
I recorded the fields of all forms I could find on the main site and compared them with what we currently have. Anything without a check is missing from the current site although not all of them may be necessary anymore

**Comment by almasaeed2010** [comment]
Nice! Thanks!

**Comment by almasaeed2010** [comment]
#### Canada Mayflower
Stakeholders requested that we remove this form

### Site Form
- List the 4 most common overstory tree species in the stand
  - We want to build a component that allows you to select and add species
- List the 4 most common seedling or shrub species in the stand
   - Same as above
- Map of stand
   - Let's just add an attachments section to sites instead of maps

### Plot form
- Name of Recorders
  - We can automatically attach the names of recorders based on who added data to the plants and measurements section of that plot.

**Comment by almasaeed2010** [comment]
Questions for stakeholders:
- Should we allow site/plot owners (in the sense that they created the site on the app) to add names of recorders? Or can we rely on automatic assignment?

**Comment by almasaeed2010** [comment]
There is a new issue for the missing fields: #57 

Closing this to move discussion to the new issue.
