### ISSUE TITLE
Activate searching and sorting

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#54]
- [x] Sites page
- [x] Plots page
- [x] Plants page
- [x] Measurements page

Also activate the search in the navbar
- [x] Navbar search should take you directly to plants of interest by tag #

**Comment by almasaeed2010** [comment]
@jwest60 I am gonna have you go over this when you have a min please

**Comment by jwest60** [comment]
### Search
- [ ] Sites
- [ ] Sites
- [ ] Sites

### Sort

**Comment by jwest60** [comment]
Done #61.
