### ISSUE TITLE
Create an admin view for data

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#58]
We need a page for admins to view data for all other users instead of just themselves. We also need to figure out how to allow users to view data from other groups they belong to.

**Comment by almasaeed2010** [comment]
Let's have a submenu for administrators or users with administration related permissions that contains all the pages available to administrators

**Comment by almasaeed2010** [comment]
We have submenu support now.And we added customizable permissions to allow access to the admin menu to appropriate users only.

**Comment by almasaeed2010** [comment]
@jwest60 since you created the data views for the groups, could you implement the same thing for admin screens?

**Comment by jwest60** [comment]
Done. #179
