### ISSUE TITLE
Groups and Admins Data Views

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#75]
We need to define new routes for admins and group members who have access to certain sites. The new routes will allow the back button to work correctly and will use the new data views to display the data. Each route should provide enough information for the data views to know how to go back and how to go forward to a sub view.

**Comment by almasaeed2010** [comment]
@jwest60 we talked about this a bit so I think you should be able to take of it. If you have questions, let me know.

**Comment by jwest60** [comment]
Pretty sure this was covered in #133, if i missed something feel free to re-open.
