### ISSUE TITLE
Sites created on group page don't appear on group page

### ISSUE THREAD

**Issue by jwest60** [statonlab/AVIDWeb#87]
Clicking New Site on the group page, filling out the form, then submitting creates the site, but doesn't appear on the group page

**Comment by almasaeed2010** [comment]
I think in general we need to figure out how to make sure new sites are auto attached to groups. I think we can do this by making the model dispatch a SiteCreatedEvent then having a listener take care of attaching it to the necessary group. This has 1 problem though, when a user creates a site it'll take up to a minute for the site to show up on the current page. We could instead simply attach the site to all the groups the user belongs to in the controller.
